### ISSUE TITLE
Android: Autocomplete using Swiftkey is broken

### ISSUE THREAD

**Issue by matthias-g** [Fmstrat/ownnote#176] opened 2015-07-06 16:33 UTC
Using Swiftkey's autocomplete feature to enter a word in a line after the first line the complete word is added to the stub instead of replacing it.

![screenshot_2015-07-06-18-23-18](https://cloud.githubusercontent.com/assets/1591161/8527425/d6f4a464-240c-11e5-8625-67286ea612f9.png)

![screenshot_2015-07-06-18-23-25](https://cloud.githubusercontent.com/assets/1591161/8527435/e33d50fe-240c-11e5-8207-4218e70d632c.png)

I'm running the app on CM 12.1 (Lollipop 5.1.1).

**Comment by Fmstrat** [comment] 2015-07-07 20:31
Duplicate of: https://github.com/Fmstrat/ownnote/issues/152

**Closed** 2015-07-07 20:31 UTC
Labels: duplicate
