### ISSUE TITLE
No editing of notes when asset-pipeline.enabled set to true

### ISSUE THREAD

**Issue by Tamsy** [Fmstrat/ownnote#203] opened 2015-07-13 10:14 UTC
ownCloud 8.0.5
PHP Version 5.6.x
mySQL 5.6.x
Apache 2.4.x

ownnote 1.03, 1.04, 1.05

Whenever I activate 'asset-pipeline.enabled' => true in ownCloud's config.php, notes through ownCloud's web interface can not be edited (the note to be edited and the formatting bar are not showing up). Also editing notes through the latest ownnote-app with Android (5.0.1) fails (the password prompt to re-login pops up instead).

Apache's logfile shows the following:
<snip>
123.123.123.123 - - [13/Jul/2015:11:46:36 +0200] "GET /assets/themes/modern/theme.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:36 +0200] "GET /assets/plugins/advlist/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/visualblocks/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/code/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/fullscreen/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/insertdatetime/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/media/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:38 +0200] "GET /assets/plugins/table/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:39 +0200] "GET /assets/plugins/contextmenu/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:39 +0200] "GET /assets/plugins/bdesk_photo/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:39 +0200] "GET /assets/plugins/autoresize/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/link/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/autolink/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/charmap/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/lists/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/anchor/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:41 +0200] "GET /assets/plugins/searchreplace/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:42 +0200] "GET /assets/plugins/preview/plugin.js HTTP/1.1" 404 2652
123.123.123.123 - - [13/Jul/2015:11:46:42 +0200] "GET /assets/plugins/print/plugin.js HTTP/1.1" 404 2652
<snip>

When enabling 'asset-pipeline.enabled' the ownnote-app searches its java-script files at the wrong location (below the directory 'assets'). In fact they are located under /apps/ownnote/js/tinymce/plugins

I have deleted all files inside the assets-directory but the outcome remains the same: As long as 'asset-pipeline.enabled' is set to 'true' notes can not be edited.

Steps to reproduce:
- Enable 'asset-pipeline.enabled' in ownCloud's config.php
- Try to edit a note through the web interface or through the Android app.

Setting 'asset-pipeline.enabled' to 'false' makes the ownnote-app work as expected.

**Comment by Fmstrat** [comment] 2015-07-14 12:58
Duplicate of https://github.com/Fmstrat/ownnote/issues/70

This is in the plan, but requires wholesale changes to the underlying editor plugin code first.

**Closed** 2015-07-14 12:58 UTC
Labels: duplicate
