### ISSUE TITLE
Problem OC 8.0.5

### ISSUE THREAD

**Issue by apg1980** [Fmstrat/ownnote#190] opened 2015-07-08 03:54 UTC
Hi,
after upgrade to oc 8.0.5 i am getting a white screen, no notes appear. change back to files app, oc is logging out everytime.

Fatal 	index 	Exception: {"Message":"CORS requires basic auth","Code":0,"Trace":"#0 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/middleware\/middlewaredispatcher.php(90): OC\\AppFramework\\Middleware\\Security\\CORSMiddleware->beforeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#1 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/http\/dispatcher.php(85): OC\\AppFramework\\Middleware\\MiddlewareDispatcher->beforeController(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#2 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/app.php(97): OC\\AppFramework\\Http\\Dispatcher->dispatch(Object(OCA\\OwnNote\\Controller\\OwnnoteApiController), 'ajaxindex')\n#3 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/routing\/routeactionhandler.php(44): OC\\AppFramework\\App::main('OwnnoteApiContr...', 'ajaxindex', Object(OC\\AppFramework\\DependencyInjection\\DIContainer), Array)\n#4 [internal function]: OC\\AppFramework\\routing\\RouteActionHandler->__invoke(Array)\n#5 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/route\/router.php(252): call_user_func(Object(OC\\AppFramework\\routing\\RouteActionHandler), Array)\n#6 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/base.php(791): OC\\Route\\Router->match('\/apps\/ownnote\/a...')\n#7 \/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/index.php(36): OC::handleRequest()\n#8 {main}","File":"\/OWNCLOUD-DATA\/opt\/bitnami\/apps\/owncloud\/htdocs\/lib\/private\/appframework\/middleware\/security\/corsmiddleware.php","Line":75}

**Comment by hulmgulm** [comment] 2015-07-08 04:37
I see the following in the browser:
NetworkError: 500 Internal Server Error - http://www.schwubb.com/oc/index.php/apps/ownnote/api/v0.2/ownnote/ajaxindex?_=1436330159493

**Comment by Fmstrat** [comment] 2015-07-08 15:23
Duplicate of: https://github.com/Fmstrat/ownnote/issues/174

**Closed by Fmstrat** 2015-07-08 15:23 UTC
