### ISSUE TITLE
OC 8.1: Archives of type text/html are not supported

### ISSUE THREAD

**Issue by beedaddy** [Fmstrat/ownnote#182] opened 2015-07-07 13:37 UTC
After upgrading ownCloud to 8.1, I'm trying to reenable ownnote. But I get the error message: "Archives of type text/html are not supported" and enabling ownnote fails. With ownCloud 8.0.x, there was no problem.
![ownnote_error](https://cloud.githubusercontent.com/assets/3264939/8547401/dd11da12-24be-11e5-8060-c6d56c087d31.png)

**Comment by beedaddy** [comment] 2015-07-07 13:55
Manually downloading the package solves the issue with this message. But now there is only a blank screen shown. No ownnote content available.

**Comment by UnnamedHero** [comment] 2015-07-07 19:23
Confirm this. I have same issue.

**Comment by Fmstrat** [comment] 2015-07-07 20:47
Duplicate of: https://github.com/Fmstrat/ownnote/issues/174 Please participate in the discussion there. Thanks.

**Closed by Fmstrat** 2015-07-07 20:47 UTC
