### ISSUE TITLE
Android: Notes created while offline are sometimes lost

### ISSUE THREAD

**Issue by dasmaetthes** [Fmstrat/ownnote#161] opened 2015-06-10 16:53 UTC
Currently it's possible only to read created notes off-line but not to add notes.
As far I added a note when the phone is off-line and close the app the Note gets lost
It would be a nice feature to have also possibility to add note when Phone is off-line
Thanks a lot
Matthias

**Comment by Fmstrat** [comment] 2015-06-11 18:35
Hi,

I'm not sure exactly what's happening for you so before I investigate can you give me the process you're going through? For instance, this works for me:
- Enter airplane mode
- Wait a few seconds to ensure all connections are dead
- Start ownNote
- Tap Create note
- Name it, save
- Exit ownNote
- Exit airplane mode
- Wait 10ish seconds to ensure all connections are alive
- Start ownNote
- Synchronization occurs, and the new note is added to the server

**Comment by dasmaetthes** [comment] 2015-06-11 18:42
- Enter airplane mode
- Wait a few seconds to ensure all connections are dead
- Start ownNote
- Tap Create note
- Name it, save
- Open it, write content, save
- Exit ownNote
- Start ownNote
- Note is lost

**Comment by Fmstrat** [comment] 2015-06-11 18:47
OK, recreated. For reference, it appears that's not when the note is lost. It's at the bottom of the listing. It's lost on resync after going back online. For some reason it only happens if the note has content, and not always. Listing this as a bug.

**Comment by dasmaetthes** [comment] 2015-06-11 18:53
Thanks, hope it will be fixed in one of next milestones

DO make it clear one more time,
The note is already lost when I open the again without going online between

**Comment by RalfWW** [comment] 2015-06-14 20:33
I can confirm this behaviour for all my tries to create a note while offline.

**Comment by Fmstrat** [comment] 2015-07-25 16:22
Not to self, test deletes: https://github.com/Fmstrat/ownnote/issues/214

**Comment by vivoforta** [comment] 2015-09-29 19:29
I also have this behavior when creating notes offline.
Android 5.0.1
Ownnote 1.0

**Comment by milankni** [comment] 2015-10-06 21:23
A risky workaround is to keep the app running and switch to launcher with "home" button. Get on-line and sync before Android kills the app ;-)

**Comment by Berni-MD** [comment] 2015-10-16 20:55
This bug is the main reason why I am not yet finally switched from Google-task to dies great 
ownnote-app! On all the other missing features I could wait.

**Comment by Fmstrat** [comment] 2015-10-21 22:00
Fixed. Turned out the reason this was hard to reproduce was actually simple. It was at the bottom of the list if the app stayed open in memory. It got deleted completely if the app left memory, or if you use a task-killer program or actively kill the task in the task manager. If @dasmaetthes follows his process exactly, I'm guessing he must be using a task killer for this to occur, or opening other apps in between.

In any event, it's fixed, and deletes work offline now, too. Even managed to fix the sorting when a note is created. It will be released with 1.01, so hopefully this helps everyone out.

**Closed by Fmstrat** 2015-10-21 22:00 UTC
Labels: bug

**Comment by Berni-MD** [comment] 2015-10-22 17:00
Das hört sich doch schon mal sehr gut an :+1:

**Comment by dasmaetthes** [comment] 2015-10-22 17:17
Thanks for fixing the bug :+1: Waiting for the update.
No I don't use any task killer or open other apps between

**Comment by caco3** [comment] 2016-05-14 12:39
As shown in https://github.com/Fmstrat/ownnote/issues/258#issuecomment-219218145, this seems not yet to be fully solved!
Tested with the version as provided in the Google Play store, 1.0, 15. June 2015!
Shouldn’t there be a newer version?
