### ISSUE TITLE
Server: Field 'shared' doesn't have a default value

### ISSUE THREAD

**Issue by kurdtkuei** [Fmstrat/ownnote#65] opened 2015-03-30 10:56 UTC
Not sure what the problem could be. I've installed ownnote and I can see it in the apps. Going into it, I can create a new note. After giving a name to a note and clicking create it comes back to the window where I can create a new note and the just created note is not showing up (so no note has been created). In the log I'm getting such error

Exception: {"Message":"An exception occurred while executing 'INSERT INTO oc_ownnote (uid, name, grouping, mtime, note) VALUES (?,?,?,?,?)' with params [\"administrator\", \"sdf\", \"\", 1427712718, \"\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'shared' doesn't have a default value","Code":0,"Trace":"#0 C:\\inetpub\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 C:\\inetpub\\owncloud\\3rdparty\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Statement.php(172): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO oc_...', Array)\n#2 C:\\inetpub\\owncloud\\lib\\private\\db\\statementwrapper.php(63): Doctrine\\DBAL\\Statement->execute(Array)\n#3 C:\\inetpub\\owncloud\\apps\\ownnote\\lib\\backend.php(264): OC_DB_StatementWrapper->execute(Array)\n#4 C:\\inetpub\\owncloud\\apps\\ownnote\\controller\\ownnoteapicontroller.php(76): createNote('', 'sdf', '')\n#5 [internal function]: OCA\\OwnNote\\Controller\\OwnnoteApiController->create()\n#6 C:\\inetpub\\owncloud\\lib\\private\\appframework\\http

Any idea what could be the Problem?

**Comment by Fmstrat** [comment] 2015-03-30 12:40
Looks like in Windows the SQL database isn't liking the format of the shared "not null" field in the DB. I will force in a blank value in the next release.

**Comment by StopTrain** [comment] 2015-03-30 14:45
Just an FYI, I can confirm this same issue on a MariaDB/MySQL host.

Running:  ALTER TABLE oc_ownnote ALTER COLUMN shared SET DEFAULT ' ';

Seems to fix it for me.

**Comment by Fmstrat** [comment] 2015-03-30 14:49
@StopTrain Glad that worked for you, and it should work for everyone, however I wouldn't recommend doing that because...

Unfortunately the underlying problem is that when defining the DB in ownCloud's XML, some systems treat "<default></default>" as no default, while others treat it is a blank string. I'm going to need to make it force a blank string in until sharing is complete and then this will be fixed for all users.

So, I wouldn't recommend your fix since I'm not sure what the long term impacts of modifying the DB manually will be as upgrades to ownNote are run.

**Comment by StopTrain** [comment] 2015-03-30 14:54
I completely agree.  I did it as a stop-gap measure helping another user out.  I'll keep my change in place to see what happens when an upgrade is performed.

**Comment by StopTrain** [comment] 2015-03-30 14:54
Oh, one more thing, when I did the change using ' ';  It treated the empty space in between as a literally empty string.  Hope that helps.

**Comment by Fmstrat** [comment] 2015-03-30 21:14
Fixed in: https://github.com/Fmstrat/ownnote/commit/c0100e32caa97059f234010ece42caa0824b7af3

Will be released in next version.

**Closed by Fmstrat** 2015-03-30 21:14 UTC
Labels: bug

**Comment by kurdtkuei** [comment] 2015-03-31 07:09
Thank you very much!
