### ISSUE TITLE
Last entry can't be deleted after import

### ISSUE THREAD

**Issue by pappel2** [Fmstrat/ownnote#154] opened 2015-06-06 15:44 UTC
I imported about 130 notes from Evernote into ownnote. In general, everything worked as described, but since the time stamps (created, modified) were not imported, I decided to delete all notes again.

Unfortunately, one note (I guess it was the first in alphabetical order) cannot be deleted. If I delete the file in the Notes folder, it reappears after some seconds.
If I click on the trash icon in the ownnote application, nothing happens.

Funny thing is, that the content of that message is deleted, but the message itself can't be removed.

**Comment by Fmstrat** [comment] 2015-06-06 16:49
Is ownNote still installed as an app? It's likely since you deleted the file and not the note in ownNote that the DB copy is still there and when you load ownNote it's recreating it from the DB record. I'm not sure of all the steps you've taken, but that's not a bug, it's a requirement to keep the system in sync with mobile devices (DB takes precedence). 

To force kill all notes without doing it in the app, run this from a shell prompt:

    echo "delete from oc_ownnote;" | mysql owncloud
    echo "delete from oc_ownnote_parts;" | mysql owncloud

That's a force kill, and will remove everything except the settings in the admin section. You could also do this manually in the app itself if it's still enabled, but it would take a while to delete 130 notes. (Mass delete is on the enhancement list)

**Comment by pappel2** [comment] 2015-06-06 19:39
ownNote is still installed as an app, and working as expected (except that one entry, that refuses to be deleted).
I was able to delete all 129 other entries via the trash symbol (with 129 clicks ;-)), but this one reappears, no matter if I click on the trash symbol or delete the file in the owncloud Notes folder.
I just tried to delete it via the Android app, but also no chance. If I want to rename it, the old name reappears. I will then try the direct "kill" from the db, as suggested.

**Comment by pappel2** [comment] 2015-06-07 15:49
I tried to delete directly via SQL commands, but unfortunately, this one entry still remains.
During the first deletiion, it said, that in the first table, some 130 lines were removed, and in the second, it was (I guess) about four.
But still, the entry remains. I did manual deletion again, but still no success. In the android client, after deletion, the client showed a message, that he loaded 127 lines, but then again displayed only this one single entry.
Could you give me any other advice, on how to remove this entry?

**Comment by pappel2** [comment] 2015-06-07 16:51
I've now installed phpmyadmin, to get a little bit more overview about the different tables.
When deleting the entry in the two tables via phpmyadmin, it's the same result.
I then saw, that in the table "oc_filecache", the entry appears several times. I don't want to delete something there, since I'm not that much into the owncloud tables.
Any idea, how to solve this?

**Comment by pappel2** [comment] 2015-06-07 17:00
Solved it :-).
It seems to be related to the filename. The filename of the original import file was "125,- € für eine Stunde Warten.html".
I logged into console, and looked into the Notes folder from there. This file was not displayed in the Owncloud web interface, but still it was recognized by the OwnNote import routine (the .htm file was displayed, like all the others).
After deletion (either via web interface, or via removing the database entries), the file was again converted to an entry immediately.
After removing the file directly via console, everything works fine again now.

May a bug (or enhancement), to catch really all files for removal after import?

**Comment by Fmstrat** [comment] 2015-06-08 18:54
Interesting, I think you may have actually located either a bug in the file API used by ownCloud apps, or in the ownCloud core files app. If this happens to you again, I would grab any logs and table records you can and submit a ticket on the ownCloud repository. 

As for the imports, I've already got an enhancement ticket for using transactions on imports and for multiple deletes. Closing this out for now, but let me know if it happens again.

**Closed by Fmstrat** 2015-06-08 18:54 UTC
Labels: help wanted
