### ISSUE TITLE
Links do not work on Server

### ISSUE THREAD

**Issue by Berni-MD** [Fmstrat/ownnote#216] opened 2015-08-03 15:16 UTC
If I have a (html) link in my note, then I can not click it in ownCloud-Server.
I still need to adjust something or is this a bug.

**Comment by Fmstrat** [comment] 2015-08-20 20:14
Nope, this is a duplicate of another report, though. For now, you may be able to control-click on the link. The issue is that if links are active, you can't click on them to edit them. So, I'm still trying to find another way around it. Thanks!

**Closed by Fmstrat** 2015-08-20 20:14 UTC

**Comment by lidense** [comment] 2015-11-10 09:31
Hello did you solve this problem, hyperlinks do not seem to work from the server.
Thanks.
dave
